# Author: Ruslan Brilenkov

# This tutorial is part of my big project 

## The main idea is to teach everybody Python, Data Science, and Machine Learning (ML) despite their educational background.

## Follow [this](https://medium.datadriveninvestor.com/python-tutorial-for-complete-beginners-from-hello-world-to-functions-47ceb8b96555) and [this](https://medium.com/mlearning-ai/machine-learning-for-complete-beginners-introduction-61b3a961b5ae) links to learn more

----

# Let us start with importing libraries

In [1]:
import numpy as np
import pandas as pd

from sklearn import neighbors, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Opening the dataset

In [2]:
# Loading dataset
data = pd.read_csv('agaricus-lepiota.data')#, header=None)

# print(data.head()) # first 5 raws

print(data.shape)

# Let us manually add the features/columns names
data.columns = ['class', 'cap-shape', 'cap-surface', 'cap-color', \
                'bruises?', 'odor', 'gill-attachment', 
                'gill-spacing' ,'gill-size', 'gill-color', 
                'stalk-shape', 'stalk-root', 'stalk-surface-above-ring', 
                'stalk-surface-below-ring', 'stalk-color-above-ring', 
                'stalk-color-below-ring', 'veil-type', 'veil-color', 
                'ring-number', 'ring-type', 'spore-print-color', 
                'population', 'habitat']
data.head()


(8123, 23)


class cap-shape cap-surface cap-color bruises? odor gill-attachment  \
0     e         x           s         y        t    a               f   
1     e         b           s         w        t    l               f   
2     p         x           y         w        t    p               f   
3     e         x           s         g        f    n               f   
4     e         x           y         y        t    a               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         b          k  ...                        s   
1            c         b          n  ...                        s   
2            c         n          n  ...                        s   
3            w         b          k  ...                        s   
4            c         b          n  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 n          n       g  
1           o         p                 n          n       m  
2           o         p                 k          s       u  
3           o         e                 n          a       g  
4           o         p                 k          n       g  

[5 rows x 23 columns]

## Selecting the attrabutes as our labels for this model
### (to reduce the size of the dataset)

## Tip: chose which parameters are the most important ones to determine the label
## For example, let us chose mostly the colors of various mushroom parts (cap, gill, veil, spore-print)

In [3]:
X = data[['cap-shape', 'cap-surface', 'cap-color', 
          'odor', 'gill-color', 'veil-color', 'spore-print-color']].values
print(X)

[['x' 's' 'y' ... 'k' 'w' 'n']
 ['b' 's' 'w' ... 'n' 'w' 'n']
 ['x' 'y' 'w' ... 'n' 'w' 'k']
 ...
 ['f' 's' 'n' ... 'n' 'o' 'b']
 ['k' 'y' 'n' ... 'b' 'w' 'w']
 ['x' 's' 'n' ... 'y' 'o' 'o']]


### Here is an issue:
### our dataset contains names (strings) instead of the numbers (integers/floats) => we cannot fetch strings into our ML algorithm

## Solution: convert strings into numbers


## Features (X) need one type of transformation, called Label Encoder

In [4]:
# defining our encoder
Lbl_Enc_X = LabelEncoder()

for col in range(len(X[0])):
    X[:, col] = Lbl_Enc_X.fit_transform(X[:, col])
    
print(X)



[[5 2 9 ... 4 2 3]
 [0 2 8 ... 5 2 3]
 [5 3 8 ... 5 2 2]
 ...
 [2 2 4 ... 5 1 0]
 [3 3 4 ... 0 2 7]
 [5 2 4 ... 11 1 4]]


## Labels (y) need another type of transformation, called Mapping

In [5]:
y = data[['class']]

# dictionary
Lbl_Map = {
    'e': 0,
    'p':1
          }

# actual convertion
y['class_2'] = y['class'].map(Lbl_Map)

print(y)
print(y['class_2'])


     class  class_2
0        e        0
1        e        0
2        p        1
3        e        0
4        e        0
...    ...      ...
8118     e        0
8119     e        0
8120     e        0
8121     p        1
8122     e        0

[8123 rows x 2 columns]
0       0
1       0
2       1
3       0
4       0
       ..
8118    0
8119    0
8120    0
8121    1
8122    0
Name: class_2, Length: 8123, dtype: int64


/home/ruslan/anaconda3/envs/astroconda/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.


In [6]:
# print(y[0:5])
# y = np.array(y)
# print(y[0:5])

to learn more about dictionaries, lists, and tuples follow [this link](https://medium.datadriveninvestor.com/python-tutorial-for-complete-beginners-from-hello-world-to-functions-47ceb8b96555)

# Let us create the model!

In [7]:
# A model is represented as an object
knn = neighbors.KNeighborsClassifier(n_neighbors=15, 
                                     weights='uniform')


In [8]:
# But our model is not ready for predictions yet. 
# It needs training!

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y['class_2'], test_size = 0.2)


In [10]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=15)

In [11]:
predictions = knn.predict(X_test)

In [12]:
# accuracy calculation
accuracy = metrics.accuracy_score(y_test, predictions)

print("Predictions = {}".format(predictions[10:15]))
print("Real labels = {}".format(y_test[10:15]))
print("Accuracy is {}".format(accuracy))

Predictions = [0 0 0 1 0]
Real labels = 1726    0
2905    0
943     0
7668    1
2139    0
Name: class_2, dtype: int64
Accuracy is 0.9815384615384616


# We got ~97% accuracy!
## Our bet on the colors as the most important elements seems to be right! 